export default {
  currentRoute: null,
  web3: {
    address: '',
    coinbase: '',
    error: null,
    instance: null,
    isInjected: false,
    networkId: ''
  },
  user: {
    // lastName: '',
    // firstName: '',
    // middleName: '',
    // fullName: '',
    // street: '',
    // city: '',
    // state: '',
    // zipCode: '',
    // country: 'US',
    // phoneNumber: '+1',
    // socialSecurityNumber: '',
    // areaNumber: '',
    // groupNumber: '',
    // sequenceNumber: '',
    // day: '',
    // month: '',
    // year: '',
    // gender: '',
    type: '',
    email: '',
    avatarCanvas: null,
    hasWeb3InjectedBrowser: false,
    hasCoinbase: false,
    isConnectedToODLLNetwork: false,
    coinbase: '',
    isValid: false,
    isPatient: false,
    canBeNewPatient: false,
    patientable: false,
    isDentist: false,
    isODLLAdmin: false,
    isODLLManager: false
  },
  isDAppReady: false
}
