// import contract from 'truffle-contract'
// import ODLLDB from '../../build/contracts/ODLLDB.json'
// import ODLLUserContract from '../../build/contracts/ODLLUser.json'
// import { APPROVED_BLOCKCHAIN_NETWORK_ID, NETWORKS } from '../util/constants'
// import soliditySha3 from 'solidity-sha3'
